env:
  browser: true
  es2021: true
extends: xo
# extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style: off
  quotes:
    - error
    - double
  no-empty: warn
  semi:
    - error
    - always
  no-unreachable: error
  no-constant-binary-expression: error
  no-unreachable-loop: error
  no-constructor-return: error
  no-await-in-loop: error
  array-callback-return: error
  require-atomic-updates: error
  no-unmodified-loop-condition: error
  no-template-curly-in-string: error
  no-self-compare: error
  no-duplicate-imports: error
  prefer-rest-params: error
  no-empty-function: error
  generator-star-spacing: off
  comma-dangle: off
  array-element-newline: off
  no-return-assign: off
  prefer-const: warn
  max-len:
    - error
    - { code: 100 }
  no-unused-expressions: warn
  no-unused-vars: warn
  camelcase: off
  new-cap: off
  quote-props: off
  no-constant-condition:
    - error
    - { checkLoops: false }
  func-names:
    - warn
    - as-needed
  no-use-before-define:
    - error
    - { functions: false }